spring.application.name=lingocamp
server.port = 8081

# spring.security.user.name = maleesha
# spring.security.user.password = maleesha

spring.security.oauth2.client.registration.google.client-id=401343658601-9q8vf9pprv0qq0amgug7pri9re8gjs9m.apps.googleusercontent.comYOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
